import {useEffect, useState} from "react";

export const useMovies = () => {

    const [movies, setMovies] = useState([]);

    useEffect(() => {

        setTimeout(() =>{
            setMovies([
                {
                    id: "1",
                    name: "JURASSIC WORLD: DOMINION ",
                    director: "Ava DuVernay",
                    year: "2023",
                    synopsis: "Exploración de los territorios inexplorados del cosmos.",
                    reviews: "Una obra maestra visual que expande la imaginación.",
                    duration: "135",
                    categoria: "Ciencia Ficción",
                    idioma: "español",
                    actores: "Michael Thompson, Olivia Chen",
                    imagen: "https://image.tmdb.org/t/p/w185/sXeWfpT1EhG7f4uBouqraOhmouH.jpg",
                    trailler:"<iframe width=\"1298\" height=\"487\" src=\"https://www.youtube.com/embed/RJ4b1ZQxPmE\" title=\"JURASSIC WORLD: DOMINION - Tráiler Oficial 2 (Universal Pictures) HD\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"50.000",
                    preciocompra:"120.000"
                },
                {
                    id: "2",
                    name: "Doctor Strange in the Multiverse of Madness ",
                    director: "Jordan Peele",
                    year: "2023",
                    synopsis: "Ocurrencias misteriosas en un pequeño pueblo revelan oscuros secretos.",
                    reviews: "Suspense y escalofríos, un thriller imprescindible.",
                    duration: "120",
                    categoria: "Suspenso",
                    idioma: "español",
                    actores: "Emma Davis, Liam Harris",
                    imagen: "https://image.tmdb.org/t/p/w185/vThe85YlGE5r7fqEVFePETqnWzk.jpg",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/aWzlQ2N6qqg\" title=\"Marvel Studios&#39; Doctor Strange in the Multiverse of Madness | Official Trailer\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
                    alquiler:"false",
                    comprada:"true",
                    precioalquiler:"80.000",
                    preciocompra:"100.000"
                },
                {
                    id: "3",
                    name: "Spider-Man No Way Home",
                    director: "Denis Villeneuve",
                    year: "2023",
                    synopsis: "Un viaje para encontrar el equilibrio en un mundo al borde del caos.",
                    reviews: "Una obra maestra visual y emocional.",
                    duration: "150",
                    categoria: "Drama",
                    idioma: "español",
                    actores: "Sophia Rodriguez, Diego Martinez",
                    imagen: "https://image.tmdb.org/t/p/w185/1z7ZQhga4AcSkQNqEU3Tf9XpxoX.jpg",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/CIRQTZ4yZrI?list=PLOx4pXZYwcTNRqz0teHJpdguIyTIf9d9T\" title=\"Mysterio Revela la Identidad de Peter - Spider-Man No Way Home (Español Latino)\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
                    alquiler:"true",
                    comprada:"false",
                    precioalquiler:"50.000",
                    preciocompra:"120.000"
                },
                {
                    id: "4",
                    name: "Eternals",
                    director: "Greta Gerwig",
                    year: "2023",
                    synopsis: "Historia de amor que viaja en el tiempo y trasciende generaciones.",
                    reviews: "Conmovedora y bellamente elaborada.",
                    duration: "128",
                    categoria: "Romance",
                    idioma: "español",
                    actores: "Lucas Johnson, Isabella Lopez",
                    imagen: "https://image.tmdb.org/t/p/w185/9sPHXiWJnae2Pqv9EfAqGs634m9.jpg",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/v1EkoQV4g5c\" title=\"Eternals de Marvel Studios | Tráiler Oficial | Doblado\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"30.000",
                    preciocompra:"90.000"
                },
                {
                    id: "5",
                    name: "Matrix 1",
                    director: "Ridley Scott",
                    year: "2023",
                    synopsis: "Exploración surrealista del subconsciente humano.",
                    reviews: "Desafiante y provocadora.",
                    duration: "140",
                    categoria: "Psicológica",
                    idioma: "español",
                    actores: "Mia Anderson, Ethan White",
                    imagen: "https://image.tmdb.org/t/p/w185/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/nNpvWBuTfrc\" title=\"The Matrix Resurrections – Official Trailer 2\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"90.000",
                    preciocompra:"220.000"
                },
                {
                    id: "6",
                    name: "Matrix recargado",
                    director: "Alfonso Cuarón",
                    year: "2023",
                    synopsis: "Un baile poético entre la luz y la oscuridad.",
                    reviews: "Arte cinematográfico en su máxima expresión.",
                    duration: "118",
                    categoria: "Cine de Autor",
                    idioma: "español",
                    actores: "Gabriel Ramirez, Sofia Perez",
                    imagen: "https://image.tmdb.org/t/p/w185/8c4a8kE7PizaGQQnditMmI1xbRp.jpg",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/nNpvWBuTfrc\" title=\"The Matrix Resurrections – Official Trailer 2\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"10.000",
                    preciocompra:"40.000"
                },
                {
                    id: "7",
                    name: "Mario Bross",
                    director: "Spike Lee",
                    year: "2023",
                    synopsis: "Exploración de la identidad cultural y el cambio social.",
                    reviews: "Potente y reflexiva.",
                    duration: "145",
                    categoria: "Comentario Social",
                    idioma: "español",
                    actores: "Luna Hernandez, Javier Rodriguez",
                    imagen: "https://image.tmdb.org/t/p/w780/1b2qmBIO91k7STcZP6Dx0Q5snU5.jpg",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/5r9JTn8FAsw\" title=\"ESTRENO 2023! Pelicula, Completa en Espanol Latino HD\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
                    alquiler:"false",
                    comprada:"true",
                    precioalquiler:"60.000",
                    preciocompra:"110.000"
                },
                {
                    id: "8",
                    name: "Enigma Efímero",
                    director: "Kathryn Bigelow",
                    year: "2023",
                    synopsis: "Desentrañando los misterios de una existencia fugaz.",
                    reviews: "Visualmente impresionante con un mensaje profundo.",
                    duration: "132",
                    categoria: "Misterio",
                    idioma: "español",
                    actores: "Aiden Campbell, Bella Sanchez",
                    imagen: "https://image.tmdb.org/t/p/w780/lyHmhoRj3zXSdeCYbs2oOXLCF4K.jpg",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/zXKHGaRxQaE\" title=\"The imitation game (Descifrando Enigma) - Trailer español\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>",
                    alquiler:"true",
                    comprada:"false",
                    precioalquiler:"50.000",
                    preciocompra:"120.000"

                },
                {
                    id: "9",
                    name: "Crónicas del Cosmos",
                    director: "James Cameron",
                    year: "2023",
                    synopsis: "Viaje a través de la vasta extensión del universo.",
                    reviews: "Un espectáculo cósmico que deja a la audiencia asombrada.",
                    duration: "155",
                    categoria: "Space Opera",
                    idioma: "español",
                    actores: "Natalie Foster, Sebastian Morales",
                    imagen: "https://image.tmdb.org/t/p/w780/8MDDAi8VnWKJdMmsxuJ1YL1wc21.jpg",
                    alquiler:"false",
                    comprada:"true",
                    precioalquiler:"50.000",
                    preciocompra:"120.000",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/zXKHGaRxQaE\" title=\"The imitation game (Descifrando Enigma) - Trailer español\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },
                {
                    id: "10",
                    name: "Beyond Horizons",
                    director: "Ava DuVernay",
                    year: "2023",
                    synopsis: "Exploring the uncharted territories of the cosmos.",
                    reviews: "A visual masterpiece that expands the imagination.",
                    duration: "135",
                    categoria: "Science Fiction",
                    idioma: "español",
                    actores: "Michael Thompson, Olivia Chen",
                    imagen: "https://image.tmdb.org/t/p/w780/cUHxmWfkp6se0Rt10Kr86bMCYDE.jpg",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"50.000",
                    preciocompra:"120.000",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/kA-Ydh0fyXc\" title=\"Hasta el Horizonte (2021) | Trailer en español\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },
                {
                    id: "11",
                    name: "Win the Windhispers ",
                    director: "Jordan Peele",
                    year: "2023",
                    synopsis: "Mysterious occurrences in a small town reveal dark secrets.",
                    reviews: "Suspenseful and chilling, a must-watch thriller.",
                    duration: "120",
                    categoria: "Thriller",
                    idioma: "español",
                    actores: "Emma Davis, Liam Harris",
                    imagen: "https://image.tmdb.org/t/p/w780/j63Clh2P6PKQQNDSruu3z7NPeNu.jpg",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"80.000",
                    preciocompra:"170.000",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/Zu2JbjuhhEY\" title=\"Win Win tráiler oficial\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },
                {
                    id: "12",
                    name: "Celestial Harmony",
                    director: "Denis Villeneuve",
                    year: "2023",
                    synopsis: "A journey to find balance in a world on the brink of chaos.",
                    reviews: "A visual and emotional masterpiece.",
                    duration: "150",
                    categoria: "Drama",
                    idioma: "español",
                    actores: "Sophia Rodriguez, Diego Martinez",
                    imagen: "https://image.tmdb.org/t/p/w780/iWOELznrV438fmyJ02GG31dULRM.jpg",
                    alquiler:"false",
                    comprada:"false",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/hC-6U8HCF8c\" title=\"Harmony - Trailer\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },
                {
                    id: "13",
                    name: "Echoes of Eternity",
                    director: "Greta Gerwig",
                    year: "2023",
                    synopsis: "Time-traveling love story that transcends generations.",
                    reviews: "Heartwarming and beautifully crafted.",
                    duration: "128",
                    categoria: "Romance",
                    idioma: "español",
                    actores: "Lucas Johnson, Isabella Lopez",
                    imagen: "https://image.tmdb.org/t/p/w780/avteWnUr5XfFYVT2dMS8ZmPtuYR.jpg",
                    alquiler:"false",
                    comprada:"false",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/zXKHGaRxQaE\" title=\"The imitation game (Descifrando Enigma) - Trailer español\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },
                {
                    id: "15",
                    name: "Infinite Dreamscape",
                    director: "Ridley Scott",
                    year: "2023",
                    synopsis: "A surreal exploration of the human subconscious.",
                    reviews: "Mind-bending and thought-provoking.",
                    duration: "140",
                    categoria: "Psychological",
                    idioma: "español",
                    actores: "Mia Anderson, Ethan White",
                    imagen: "https://image.tmdb.org/t/p/w780/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"150.000",
                    preciocompra:"520.000",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/UKFjeglbNDg\" title=\"ESTO ES INFINITE Tráiler Español Latino (2021) Mark Wahlberg\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },
                {
                    id: "16",
                    name: "Serenade of Shadows",
                    director: "Alfonso Cuarón",
                    year: "2023",
                    synopsis: "A poetic dance between light and darkness.",
                    reviews: "Cinematic artistry at its finest.",
                    duration: "118",
                    categoria: "Art House",
                    idioma: "español",
                    actores: "Gabriel Ramirez, Sofia Perez",
                    imagen: "https://image.tmdb.org/t/p/w780/xgGGinKRL8xeRkaAR9RMbtyk60y.jpg",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"30.000",
                    preciocompra:"140.000",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/PpRt3oGPLTI\" title=\"Resistencia en Star+\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },
                {
                    id: "17",
                    name: "Whirlwind Whispers",
                    director: "Spike Lee",
                    year: "2023",
                    synopsis: "An exploration of cultural identity and societal change.",
                    reviews: "Powerful and thought-provoking.",
                    duration: "145",
                    categoria: "Social Commentary",
                    idioma: "español",
                    actores: "Luna Hernandez, Javier Rodriguez",
                    imagen: "https://image.tmdb.org/t/p/w780/4q8yxTRcztBW8eMgoqziiELyHhQ.jpg",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"50.000",
                    preciocompra:"120.000",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/JRD1nWVlQX4\" title=\"Reacher - Temporada 2 | Prime Video\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },
                {
                    id: "18",
                    name: "Interstellar",
                    director: "Kathryn Bigelow",
                    year: "2023",
                    synopsis: "Unraveling the mysteries of a fleeting existence.",
                    reviews: "Visually stunning with a profound message.",
                    duration: "132",
                    categoria: "Mystery",
                    idioma: "español",
                    actores: "Aiden Campbell, Bella Sanchez",
                    imagen: "https://image.tmdb.org/t/p/w185/jd6Hi6Jbi8vdbaaA2U35zq2DVtp.jpg",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"90.000",
                    preciocompra:"180.000",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/HTvJl71zmf4\" title=\"4 Minutes of Interstellar in 4K\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },
                {
                    id: "19",
                    name: "The Black Hole Theory",
                    director: "James Cameron",
                    year: "2023",
                    synopsis: "Journeying through the vast expanse of the universe.",
                    reviews: "A cosmic spectacle that leaves audiences in awe.",
                    duration: "155",
                    categoria: "Space Opera",
                    idioma: "español",
                    actores: "Natalie Foster, Sebastian Morales",
                    imagen: "https://image.tmdb.org/t/p/w185/xXdW84shjNAzK38CYOAsDR7JG6y.jpg",
                    alquiler:"false",
                    comprada:"false",
                    precioalquiler:"50.000",
                    preciocompra:"120.000",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/OoUVSHDbAeM\" title=\"Stephen Hawking Discovers The Black Hole Theory | The Theory Of Everything (2014) | Screen Bites\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                },
                {
                    id: "20",
                    name: "KUNG FU PANDA",
                    director: "Martin Scorsese",
                    year: "2023",
                    synopsis: "A fantastical adventure into realms of enchantment.",
                    reviews: "Magical and enchanting storytelling.",
                    duration: "125",
                    categoria: "Fantasy",
                    idioma: "español",
                    actores: "Daniel Rivera, Isabella Cruz",
                    imagen: "https://image.tmdb.org/t/p/w185/u1WvYS8FRczTY3hv3CBBQzf1vht.jpg",
                    alquiler:"false",
                    comprada:"true",
                    precioalquiler:"50.000",
                    preciocompra:"90.000",
                    trailler: "<iframe width=\"1258\" height=\"480\" src=\"https://www.youtube.com/embed/NSBSEj112Zk\" title=\"KUNG FU PANDA 4 Trailer (2024)\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>"
                }
            ]);
        }, 2500)
    }, []);
    return movies;
}